# Generated by Django 5.2.3 on 2025-07-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='couple',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
