# Generated by Django 5.2.3 on 2025-07-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0002_couple_qr_couple_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='qr',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qr/'),
        ),
    ]
