# Generated by Django 5.2.3 on 2025-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple', '0003_alter_couple_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
